spring:
  profiles:
    active: mysql, jwt
  batch:
    jdbc:
      initialize-schema: always
  jpa:
    hibernate:
      ddl-auto: validate

server:
  port: 8888

fcm:
  secret: firebase-kw-dormitory.json